import {useMutation,useQuery,useQueryClient} from '@tanstack/react-query';
import {Download,Edit3,Landmark,Plus,QrCode,Trash2,Upload} from 'lucide-react';
import jsQR from 'jsqr';
import {FormEvent,useState} from 'react';
import {apiClient} from '../../../core/api/client';
import {Badge} from '../../../shared/components/Badge';
import {PageHeader} from '../../../shared/components/PageHeader';
import {TableEmpty} from '../../../shared/components/TableEmpty';

interface BankAccount{id:number;bankCode:string;bankName:string;accountNumber:string;accountName:string;enabled:boolean;qrImageUrl?:string|null}
const banks=[['VCB','Vietcombank','970436'],['BIDV','BIDV','970418'],['ICB','VietinBank','970415'],['VBA','Agribank','970405'],['MB','MB Bank','970422'],['TCB','Techcombank','970407'],['ACB','ACB','970416'],['VPB','VPBank','970432'],['TPB','TPBank','970423'],['STB','Sacombank','970403'],['HDB','HDBank','970437'],['VIB','VIB','970441'],['SHB','SHB','970443'],['OCB','OCB','970448'],['MSB','MSB','970426'],['SEAB','SeABank','970440'],['LPB','LPBank','970449'],['NAB','Nam A Bank','970428'],['BAB','Bac A Bank','970409'],['KLB','KienlongBank','970452']];
const empty={bankCode:'',bankName:'',accountNumber:'',accountName:'',enabled:true};
const generatedQr=(item:BankAccount)=>`https://img.vietqr.io/image/${encodeURIComponent(item.bankCode)}-${encodeURIComponent(item.accountNumber)}-compact2.png?accountName=${encodeURIComponent(item.accountName)}`;
function tlv(value:string){const result:Record<string,string>={};for(let index=0;index+4<=value.length;){const tag=value.slice(index,index+2),length=Number(value.slice(index+2,index+4));if(!Number.isFinite(length)||index+4+length>value.length)break;result[tag]=value.slice(index+4,index+4+length);index+=4+length;}return result;}
function readVietQr(payload:string){const root=tlv(payload),merchant=tlv(root['38']||''),account=tlv(merchant['01']||''),bin=account['00']||'',number=account['01']||'',option=banks.find(item=>item[2]===bin);if(!option||!number)throw Error('QR không chứa thông tin tài khoản VietQR được hỗ trợ');return{bankCode:option[0],bankName:option[1],accountNumber:number,accountName:(root['59']||'').trim().toUpperCase()};}
async function cropQr(file:File){const image=await createImageBitmap(file),scan=document.createElement('canvas');scan.width=image.width;scan.height=image.height;const ctx=scan.getContext('2d',{willReadFrequently:true});if(!ctx)throw Error('Không mở được ảnh');ctx.drawImage(image,0,0);const qr=jsQR(ctx.getImageData(0,0,scan.width,scan.height).data,scan.width,scan.height);if(!qr)throw Error('Không nhận diện được QR');const pts=Object.values(qr.location).filter(value=>typeof value==='object'&&value&&'x'in value&&'y'in value) as {x:number;y:number}[];const minX=Math.min(...pts.map(p=>p.x)),maxX=Math.max(...pts.map(p=>p.x)),minY=Math.min(...pts.map(p=>p.y)),maxY=Math.max(...pts.map(p=>p.y));const side=Math.max(maxX-minX,maxY-minY)*1.18,cx=(minX+maxX)/2,cy=(minY+maxY)/2,left=Math.max(0,Math.min(scan.width-side,cx-side/2)),top=Math.max(0,Math.min(scan.height-side,cy-side/2)),actual=Math.min(side,scan.width-left,scan.height-top),out=document.createElement('canvas');out.width=out.height=900;const target=out.getContext('2d');if(!target)throw Error('Không cắt được QR');target.fillStyle='#fff';target.fillRect(0,0,900,900);target.imageSmoothingEnabled=false;target.drawImage(scan,left,top,actual,actual,0,0,900,900);image.close();return out.toDataURL('image/png');}

async function decodeQr(file:File){const image=await createImageBitmap(file),canvas=document.createElement('canvas');canvas.width=image.width;canvas.height=image.height;const context=canvas.getContext('2d',{willReadFrequently:true});if(!context)throw Error('Không mở được ảnh');context.drawImage(image,0,0);const qr=jsQR(context.getImageData(0,0,canvas.width,canvas.height).data,canvas.width,canvas.height);image.close();if(!qr)throw Error('Không nhận diện được mã QR');return readVietQr(qr.data);}

export function BankAccountsPage(){
 const client=useQueryClient(),[editing,setEditing]=useState<BankAccount|'new'|null>(null),[preview,setPreview]=useState<BankAccount|null>(null),[form,setForm]=useState(empty),[uploading,setUploading]=useState(false),[error,setError]=useState(''),[pendingQr,setPendingQr]=useState('');
 const{data=[]}=useQuery({queryKey:['bank-accounts'],queryFn:async()=>(await apiClient.get<BankAccount[]>('/admin/bank-accounts')).data});
 const refresh=()=>client.invalidateQueries({queryKey:['bank-accounts']});
 const payload=()=>({bank_code:form.bankCode,bank_name:form.bankName,account_number:form.accountNumber,account_name:form.accountName,enabled:form.enabled});
 const save=useMutation({mutationFn:()=>editing==='new'?apiClient.post<BankAccount>('/admin/bank-accounts',payload()):apiClient.put<BankAccount>(`/admin/bank-accounts/${(editing as BankAccount).id}`,payload()),onSuccess:async response=>{if(pendingQr)await apiClient.put(`/admin/bank-accounts/${response.data.id}/qr`,{image_data:pendingQr});setPendingQr('');refresh();setEditing(null)}}),remove=useMutation({mutationFn:(id:number)=>apiClient.delete(`/admin/bank-accounts/${id}`),onSuccess:refresh});
 function submit(e:FormEvent){e.preventDefault();save.mutate()}
 function selectBank(code:string){const selected=banks.find(item=>item[0]===code);setForm({...form,bankCode:code,bankName:selected?.[1]||''})}
 async function upload(file:File,item:BankAccount){setUploading(true);setError('');try{const image_data=await cropQr(file);const{data:updated}=await apiClient.put<BankAccount>(`/admin/bank-accounts/${item.id}/qr`,{image_data});setPreview(updated);refresh();}catch(e){setError(e instanceof Error?e.message:'Không xử lý được ảnh');}finally{setUploading(false)}}
 async function scanAndFill(file:File){setUploading(true);setError('');try{const info=await decodeQr(file),image=await cropQr(file);setForm({...info,enabled:true});setPendingQr(image);setEditing('new');}catch(e){setError(e instanceof Error?e.message:'Không đọc được thông tin QR');alert(e instanceof Error?e.message:'Không đọc được thông tin QR');}finally{setUploading(false)}}
 async function download(item:BankAccount){const url=item.qrImageUrl||generatedQr(item);try{const blob=await(await fetch(url)).blob(),a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download=`vietqr-${item.bankCode}-${item.accountNumber}.png`;a.click();URL.revokeObjectURL(a.href);}catch{window.open(url,'_blank','noopener,noreferrer')}}
 return <div className="page"><PageHeader eyebrow="PAYMENTS / AUTO RECONCILIATION" title="Ngân hàng & VietQR" description="Tài khoản nhận tiền và QR. Giá token được quản lý tại Model Catalog." action={<div className="row-actions"><label className="button ghost qr-upload"><Upload/> {uploading?'Đang đọc QR...':'Quét QR tự điền'}<input type="file" accept="image/*" disabled={uploading} onChange={e=>{const file=e.target.files?.[0];if(file)void scanAndFill(file);e.target.value=''}}/></label><button className="button primary" onClick={()=>{setPendingQr('');setForm(empty);setEditing('new')}}><Plus/> Thêm thủ công</button></div>}/>
 <article className="card table-card"><div className="table-section-heading"><div><p className="eyebrow">RECEIVING ACCOUNTS</p><h3>{data.length} tài khoản ngân hàng</h3></div><span>Webhook SePay</span></div>{data.length?<div className="table-wrap"><table><thead><tr><th>Ngân hàng</th><th>Số tài khoản</th><th>Chủ tài khoản</th><th>Trạng thái</th><th>Thao tác</th></tr></thead><tbody>{data.map(item=><tr key={item.id}><td><b>{item.bankName}</b><small className="block">{item.bankCode}</small></td><td>{item.accountNumber}</td><td>{item.accountName}</td><td><Badge tone={item.enabled?'success':'neutral'}>{item.enabled?'ĐANG NHẬN':'ĐÃ TẮT'}</Badge></td><td><div className="row-actions"><button className="icon-button" title="QR" onClick={()=>setPreview(item)}><QrCode/></button><button className="icon-button" title="Sửa" onClick={()=>{setForm(item);setEditing(item)}}><Edit3/></button><button className="icon-button danger-text" title="Tắt" onClick={()=>confirm('Tắt tài khoản này?')&&remove.mutate(item.id)}><Trash2/></button></div></td></tr>)}</tbody></table></div>:<TableEmpty message="Chưa có tài khoản nhận tiền."/>}</article>
 {editing&&<div className="modal-layer" onClick={()=>setEditing(null)}><form className="modal" onSubmit={submit} onClick={e=>e.stopPropagation()}><p className="eyebrow">BANK ACCOUNT</p><h2>Thông tin nhận tiền</h2><label>Ngân hàng<select value={form.bankCode} onChange={e=>selectBank(e.target.value)} required><option value="">Chọn ngân hàng</option>{banks.map(([code,name])=><option key={code} value={code}>{name} ({code})</option>)}</select></label><label>Số tài khoản<input value={form.accountNumber} onChange={e=>setForm({...form,accountNumber:e.target.value.replace(/\s/g,'')})} required/></label><label>Tên chủ tài khoản<input value={form.accountName} onChange={e=>setForm({...form,accountName:e.target.value.toUpperCase()})} required/></label><label className="switch-row"><span><b>Cho phép nhận tiền</b><small>Khách có thể chọn ngân hàng này khi nạp.</small></span><input type="checkbox" checked={form.enabled} onChange={e=>setForm({...form,enabled:e.target.checked})}/></label>{save.isError&&<p className="form-error">Không thể lưu. Kiểm tra số tài khoản.</p>}<div className="modal-actions"><button type="button" className="button ghost" onClick={()=>setEditing(null)}>Hủy</button><button className="button primary"><Landmark/> Lưu</button></div></form></div>}
 {preview&&<div className="modal-layer" onClick={()=>setPreview(null)}><article className="modal qr-payment" onClick={e=>e.stopPropagation()}><p className="eyebrow">QR PREVIEW</p><h2>{preview.bankName}</h2><img src={preview.qrImageUrl?`${preview.qrImageUrl}?v=${Date.now()}`:generatedQr(preview)} alt="QR nhận tiền"/><dl><dt>Số tài khoản</dt><dd>{preview.accountNumber}</dd><dt>Chủ tài khoản</dt><dd>{preview.accountName}</dd></dl><p>Upload ảnh QR bất kỳ, hệ thống tự nhận diện và cắt phần thừa.</p>{error&&<p className="form-error">{error}</p>}<div className="modal-actions"><button className="button ghost" onClick={()=>setPreview(null)}>Đóng</button><label className="button ghost qr-upload"><Upload/> {uploading?'Đang cắt...':'Upload & tự cắt'}<input type="file" accept="image/*" disabled={uploading} onChange={e=>{const file=e.target.files?.[0];if(file)void upload(file,preview);e.target.value=''}}/></label><button className="button primary" onClick={()=>void download(preview)}><Download/> Tải QR</button></div></article></div>}</div>;
}
