import { useQuery } from '@tanstack/react-query';
import { ArrowDownLeft, ArrowUpRight, Landmark } from 'lucide-react';
import { apiClient } from '../../../core/api/client';
import { PageHeader } from '../../../shared/components/PageHeader';
import { Badge } from '../../../shared/components/Badge';
import { formatVnd } from '../../../shared/utils/format';
import { usePagination } from '../../../shared/hooks/usePagination';
import { TablePagination } from '../../../shared/components/TablePagination';
import { TableEmpty } from '../../../shared/components/TableEmpty';

interface Finance { revenue: number; gatewayCost: number; profit: number; pending: number }
interface AdminTransaction { id:number;userName:string;userEmail:string;type:'credit'|'debit';amount:number;description:string;createdAt:string }
export function FinancePage() { const { data } = useQuery({ queryKey: ['finance'], queryFn: async () => (await apiClient.get<Finance>('/admin/finance')).data }); const {data:transactions=[]}=useQuery({queryKey:['admin-transactions'],queryFn:async()=>(await apiClient.get<AdminTransaction[]>('/admin/transactions')).data}); const pagination=usePagination(transactions,10); return <div className="page"><PageHeader eyebrow="SUPER ADMIN / FINANCE" title="Dong tien" description="Ledger bat bien cho moi giao dich credit va debit."/><section className="metric-grid finance-grid"><FinanceMetric icon={<ArrowDownLeft/>} label="Tien khach nap" value={formatVnd(data?.revenue ?? 0)}/><FinanceMetric icon={<ArrowUpRight/>} label="Chi phi gateway" value={formatVnd(data?.gatewayCost ?? 0)}/><FinanceMetric icon={<Landmark/>} label="Loi nhuan gop" value={formatVnd(data?.profit ?? 0)}/></section><article className="card table-card"><div className="table-section-heading"><div><p className="eyebrow">IMMUTABLE LEDGER</p><h3>Lich su dong tien</h3></div><span>{transactions.length} giao dich</span></div>{transactions.length?<div className="table-wrap"><table><thead><tr><th>Thoi gian</th><th>Tai khoan</th><th>Loai</th><th>So tien</th><th>Noi dung</th></tr></thead><tbody>{pagination.paginatedItems.map(tx=><tr key={tx.id}><td>{tx.createdAt}</td><td><b>{tx.userName}</b><small className="block">{tx.userEmail}</small></td><td><Badge tone={tx.type==='credit'?'success':'warning'}>{tx.type.toUpperCase()}</Badge></td><td className={tx.type}>{tx.type==='credit'?'+':'-'}{formatVnd(tx.amount)}</td><td>{tx.description}</td></tr>)}</tbody></table></div>:<TableEmpty/>}<TablePagination page={pagination.page} pageSize={pagination.pageSize} totalItems={pagination.totalItems} totalPages={pagination.totalPages} onPageChange={pagination.setPage} onPageSizeChange={pagination.changePageSize}/></article></div>; }
function FinanceMetric({ icon, label, value }: { icon: React.ReactNode; label: string; value: string }) { return <article className="metric-card"><span className="metric-icon">{icon}</span><p>{label}</p><strong>{value}</strong><small>CAP NHAT REAL-TIME</small></article>; }
