import { useMutation, useQuery, useQueryClient } from '@tanstack/react-query';
import { Copy, Edit3, Plus, Route, Trash2 } from 'lucide-react';
import { FormEvent, useMemo, useState } from 'react';
import { apiClient } from '../../../core/api/client';
import type { Model } from '../../../core/types';
import { Badge } from '../../../shared/components/Badge';
import { PageHeader } from '../../../shared/components/PageHeader';
import { TableEmpty } from '../../../shared/components/TableEmpty';

interface RoutingPool { id:number;name:string;modelId:string;provider:string;strategy:string;maxConcurrency:number;perUserConcurrency:number;cooldownSeconds:number;enabled:boolean;connectionIds:string[];active:number;cooldownRemaining:number }
interface RouterConnection { id:string;provider:string;name:string;email?:string;isActive:boolean }
interface PoolForm { name:string;modelId:string;provider:string;strategy:string;maxConcurrency:number;perUserConcurrency:number;cooldownSeconds:number;enabled:boolean;connectionIds:string[] }
const emptyPool:PoolForm={name:'',modelId:'',provider:'',strategy:'round-robin',maxConcurrency:10,perUserConcurrency:2,cooldownSeconds:60,enabled:true,connectionIds:[]};
function providerKey(value:string){const key=value.toLowerCase();return key==='cx'||key==='openai'?'codex':key==='ag'?'antigravity':key;}

export function RoutingPoolsPage(){
  const queryClient=useQueryClient();
  const [editing,setEditing]=useState<RoutingPool|'new'|null>(null);
  const [form,setForm]=useState<PoolForm>(emptyPool);
  const {data:pools=[]}=useQuery({queryKey:['routing-pools'],queryFn:async()=>(await apiClient.get<RoutingPool[]>('/admin/routing-pools')).data,refetchInterval:10000});
  const {data:models=[]}=useQuery({queryKey:['admin-models'],queryFn:async()=>(await apiClient.get<Model[]>('/admin/router/models')).data});
  const {data:connectionData}=useQuery({queryKey:['router-connections'],queryFn:async()=>(await apiClient.get<{connections:RouterConnection[]}>('/admin/router/connections')).data});
  const connections=connectionData?.connections??[];
  const matchingConnections=useMemo(()=>connections.filter(item=>!form.provider||providerKey(item.provider)===providerKey(form.provider)),[connections,form.provider]);
  const refresh=()=>queryClient.invalidateQueries({queryKey:['routing-pools']});
  const payload=()=>({name:form.name,model_id:form.modelId,provider:form.provider,strategy:form.strategy,max_concurrency:form.maxConcurrency,per_user_concurrency:form.perUserConcurrency,cooldown_seconds:form.cooldownSeconds,enabled:form.enabled,connection_ids:form.connectionIds});
  const save=useMutation({mutationFn:()=>editing==='new'?apiClient.post('/admin/routing-pools',payload()):apiClient.put(`/admin/routing-pools/${(editing as RoutingPool).id}`,payload()),onSuccess:()=>{refresh();setEditing(null);}});
  const remove=useMutation({mutationFn:(id:number)=>apiClient.delete(`/admin/routing-pools/${id}`),onSuccess:refresh});
  function openEdit(pool:RoutingPool){setEditing(pool);setForm({name:pool.name,modelId:pool.modelId,provider:pool.provider,strategy:pool.strategy,maxConcurrency:pool.maxConcurrency,perUserConcurrency:pool.perUserConcurrency,cooldownSeconds:pool.cooldownSeconds,enabled:pool.enabled,connectionIds:pool.connectionIds});}
  function chooseModel(modelId:string){const model=models.find(item=>item.id===modelId);setForm(previous=>({...previous,modelId,provider:model?.provider??'',connectionIds:[]}));}
  function toggleConnection(id:string){setForm(previous=>({...previous,connectionIds:previous.connectionIds.includes(id)?previous.connectionIds.filter(item=>item!==id):[...previous.connectionIds,id]}));}
  function submit(event:FormEvent){event.preventDefault();save.mutate();}
  function openSample(){const model=models[0];setForm({...emptyPool,name:model?`Pool ${model.displayName}`:'Pool dùng chung',modelId:model?.id??'',provider:model?.provider??'',maxConcurrency:10,perUserConcurrency:2,cooldownSeconds:60,connectionIds:model?connections.filter(item=>providerKey(item.provider)===providerKey(model.provider)&&item.isActive).map(item=>item.id):[]});setEditing('new');}
  return <div className="page"><PageHeader eyebrow="TRAFFIC CONTROL / 9ROUTER" title="Routing Pools" description="Giới hạn tải theo model và user để tránh nhiều request dồn lên cùng tài khoản provider." action={<div className="row-actions"><button className="button ghost" onClick={openSample}><Copy/> Dùng cấu hình mẫu</button><button className="button primary" onClick={()=>{setForm(emptyPool);setEditing('new');}}><Plus/> Tạo pool</button></div>}/>
    <section className="pool-example card"><div><p className="eyebrow">MẪU KHUYẾN NGHỊ</p><h3>10 request tổng · 2 request/user · cooldown 60 giây</h3><p>Ví dụ 5 khách cùng gọi một model: mỗi khách tối đa 2 request đang chạy. Pool nhận tối đa 10 request; request vượt giới hạn nhận HTTP 429 và thử lại sau.</p></div><Badge tone="success">ROUND ROBIN</Badge></section>
    <article className="card table-card"><div className="table-section-heading"><div><p className="eyebrow">CAPACITY POLICIES</p><h3>{pools.length} pool đang quản lý</h3></div><span>{pools.filter(item=>item.enabled).length} active</span></div>{pools.length?<div className="table-wrap"><table><thead><tr><th>Pool / Model</th><th>Provider</th><th>Chiến lược</th><th>Tải</th><th>Mỗi user</th><th>Cooldown</th><th>Trạng thái</th><th>Thao tác</th></tr></thead><tbody>{pools.map(pool=><tr key={pool.id}><td><b>{pool.name}</b><small className="block">{pool.modelId} · {pool.connectionIds.length} tài khoản</small></td><td><Badge tone="violet">{pool.provider.toUpperCase()}</Badge></td><td>{pool.strategy}</td><td><b>{pool.active}/{pool.maxConcurrency}</b></td><td>{pool.perUserConcurrency}</td><td>{pool.cooldownRemaining>0?<Badge tone="warning">{pool.cooldownRemaining}s</Badge>:`${pool.cooldownSeconds}s`}</td><td><Badge tone={pool.enabled?'success':'neutral'}>{pool.enabled?'ĐANG DÙNG':'TẠM TẮT'}</Badge></td><td><div className="row-actions"><button className="icon-button" title="Sửa pool" onClick={()=>openEdit(pool)}><Edit3/></button><button className="icon-button danger-text" title="Xóa pool" onClick={()=>confirm(`Xóa pool ${pool.name}?`)&&remove.mutate(pool.id)}><Trash2/></button></div></td></tr>)}</tbody></table></div>:<TableEmpty message="Chưa có routing pool. Tạo pool đầu tiên để bảo vệ model dùng chung."/>}</article>
    {editing&&<div className="modal-layer" onClick={()=>setEditing(null)}><form className="modal routing-pool-modal" onSubmit={submit} onClick={event=>event.stopPropagation()}><p className="eyebrow">CAPACITY POLICY</p><h2>{editing==='new'?'Tạo routing pool':'Cập nhật routing pool'}</h2><label>Tên pool<input value={form.name} onChange={event=>setForm({...form,name:event.target.value})} required/></label><label>Model<select value={form.modelId} onChange={event=>chooseModel(event.target.value)} required><option value="">Chọn model</option>{models.map(model=><option key={model.id} value={model.id}>{model.displayName} ({model.id})</option>)}</select></label><div className="form-columns"><label>Giới hạn tổng<input type="number" min="1" max="1000" value={form.maxConcurrency} onChange={event=>setForm({...form,maxConcurrency:Number(event.target.value)})}/></label><label>Mỗi user<input type="number" min="1" max="100" value={form.perUserConcurrency} onChange={event=>setForm({...form,perUserConcurrency:Number(event.target.value)})}/></label></div><div className="form-columns"><label>Chiến lược<select value={form.strategy} onChange={event=>setForm({...form,strategy:event.target.value})}><option value="round-robin">Round robin</option><option value="fill-first">Fill first</option><option value="sticky">Sticky</option></select></label><label>Cooldown (giây)<input type="number" min="1" max="3600" value={form.cooldownSeconds} onChange={event=>setForm({...form,cooldownSeconds:Number(event.target.value)})}/></label></div><fieldset className="connection-picker"><legend>Tài khoản provider ({form.provider||'chọn model trước'})</legend>{matchingConnections.length?matchingConnections.map(item=><label key={item.id}><input type="checkbox" checked={form.connectionIds.includes(item.id)} onChange={()=>toggleConnection(item.id)}/><span><b>{item.name}</b><small>{item.email||item.id} · {item.isActive?'active':'đang tắt'}</small></span></label>):<p>Không có tài khoản trùng provider. Hãy thêm tại menu Providers.</p>}</fieldset><label className="switch-row"><span><b>Kích hoạt pool</b><small>Áp dụng giới hạn cho request của model này.</small></span><input type="checkbox" checked={form.enabled} onChange={event=>setForm({...form,enabled:event.target.checked})}/></label>{save.isError&&<p className="form-error">Không thể lưu pool. Model có thể đã thuộc pool khác.</p>}<div className="modal-actions"><button type="button" className="button ghost" onClick={()=>setEditing(null)}>Hủy</button><button className="button primary" disabled={save.isPending}><Route/>{save.isPending?'Đang lưu...':'Lưu pool'}</button></div></form></div>}
  </div>;
}
