import { useMutation, useQuery, useQueryClient } from '@tanstack/react-query';
import { Activity, Calculator, CloudCog, Edit3, Plus, RefreshCw, Search, Trash2 } from 'lucide-react';
import { FormEvent, useMemo, useState } from 'react';
import { apiClient } from '../../../core/api/client';
import type { Model } from '../../../core/types';
import { PageHeader } from '../../../shared/components/PageHeader';
import { Badge } from '../../../shared/components/Badge';
import { formatVnd } from '../../../shared/utils/format';
import { usePagination } from '../../../shared/hooks/usePagination';
import { TablePagination } from '../../../shared/components/TablePagination';
import { TableEmpty } from '../../../shared/components/TableEmpty';

const emptyModel = { id:'', displayName:'', provider:'', inputPrice:1, outputPrice:1, enabled:true };

export function RouterPage() {
  const client = useQueryClient(); const [editing,setEditing] = useState<Model | 'new' | null>(null); const [form,setForm] = useState<Model>(emptyModel); const [query,setQuery]=useState('');
  const [calculator,setCalculator]=useState<Model|null>(null); const [sampleTokens,setSampleTokens]=useState({input:1000,output:500});
  const [bulkPricing,setBulkPricing]=useState(false); const [bulkForm,setBulkForm]=useState({inputPrice:1500,outputPrice:3500});
  const { data = [] } = useQuery({ queryKey: ['admin-models'], queryFn: async () => (await apiClient.get<Model[]>('/admin/router/models')).data });
  const { data: status } = useQuery({ queryKey:['router-status'], queryFn: async () => (await apiClient.get<{connected:boolean;baseUrl:string}>('/admin/router/status')).data, refetchInterval:30000 });
  const refresh = () => client.invalidateQueries({queryKey:['admin-models']});
  const sync = useMutation({ mutationFn: () => apiClient.post('/admin/router/sync'), onSuccess: refresh });
  const save = useMutation({ mutationFn: async () => { if (editing === 'new') return await apiClient.post('/admin/router/models',{id:form.id,display_name:form.displayName,provider:form.provider,input_price:form.inputPrice,output_price:form.outputPrice,enabled:form.enabled}); return await apiClient.patch(`/admin/router/models/${encodeURIComponent(form.id)}`,{display_name:form.displayName,provider:form.provider,input_price:form.inputPrice,output_price:form.outputPrice,enabled:form.enabled}); }, onSuccess:()=>{refresh();setEditing(null);} });
  const remove = useMutation({ mutationFn: (id:string) => apiClient.delete(`/admin/router/models/${encodeURIComponent(id)}`), onSuccess:refresh });
  const filtered=useMemo(()=>data.filter(model=>`${model.id} ${model.displayName} ${model.provider}`.toLowerCase().includes(query.toLowerCase())),[data,query]);
  const applyBulk=useMutation({mutationFn:(prices:{input:number;output:number})=>apiClient.post('/admin/router/models/bulk-pricing',{input_price:prices.input,output_price:prices.output,model_ids:filtered.map(item=>item.id)}),onSuccess:()=>{refresh();setBulkPricing(false);}});
  const pagination=usePagination(filtered,10);
  function submit(e:FormEvent){e.preventDefault();save.mutate();}
  return <div className="page"><PageHeader eyebrow="INFRASTRUCTURE / 9ROUTER" title="Gateway & Model Catalog" description="CRUD catalog, giá bán và trạng thái model." action={<div className="row-actions"><button className="button ghost" onClick={()=>setBulkPricing(true)}><Calculator/> Áp giá hàng loạt</button><button className="button ghost" onClick={() => {setForm(emptyModel);setEditing('new');}}><Plus/> Thêm model</button><button className="button primary" onClick={() => sync.mutate()}><RefreshCw/> {sync.isPending ? 'Đang đồng bộ...' : 'Đồng bộ 9Router'}</button></div>}/>
    <section className="router-status card"><span className="router-icon"><CloudCog/></span><div><p className="eyebrow">UPSTREAM STATUS</p><h2>9Router {status?.connected ? 'connected' : 'not reachable'}</h2><span>{status?.baseUrl ?? 'Dang kiem tra...'} · Health endpoint: /api/health</span></div><Badge tone={status?.connected ? 'success' : 'danger'}><Activity/> {status?.connected ? 'HEALTHY' : 'OFFLINE'}</Badge></section>
    <article className="card table-card"><div className="table-section-heading"><div><p className="eyebrow">MODEL CATALOG</p><h3>{data.length} model trong catalog</h3></div><div className="table-search"><Search/><input value={query} onChange={(e)=>setQuery(e.target.value)} placeholder="Tim model, provider..."/></div></div>{filtered.length ? <div className="table-wrap"><table><thead><tr><th>Model</th><th>Provider</th><th>Giá input / 1M</th><th>Giá output / 1M</th><th>Trạng thái</th><th>Thao tác</th></tr></thead><tbody>{pagination.paginatedItems.map((model) => <tr key={model.id}><td><b>{model.displayName}</b><small className="block">{model.id}</small></td><td>{model.provider}</td><td>{formatVnd(model.inputPrice)}<small className="block">{formatVnd(model.inputPrice/1_000_000)} / token</small></td><td>{formatVnd(model.outputPrice)}<small className="block">{formatVnd(model.outputPrice/1_000_000)} / token</small></td><td><Badge tone={model.enabled ? 'success' : 'neutral'}>{model.enabled ? 'ĐANG BÁN' : 'TẠM DỪNG'}</Badge></td><td><div className="row-actions"><button className="icon-button" title="Tính thử chi phí" onClick={()=>setCalculator(model)}><Calculator/></button><button className="icon-button" title="Sửa model" onClick={() => {setForm(model);setEditing(model);}}><Edit3/></button><button className="icon-button danger-text" title="Xóa model" onClick={() => confirm(`Xoa model ${model.id}?`) && remove.mutate(model.id)}><Trash2/></button></div></td></tr>)}</tbody></table></div>:<TableEmpty message="Khong tim thay model phu hop."/>}<TablePagination page={pagination.page} pageSize={pagination.pageSize} totalItems={pagination.totalItems} totalPages={pagination.totalPages} onPageChange={pagination.setPage} onPageSizeChange={pagination.changePageSize}/></article>
    {editing && <div className="modal-layer" onClick={() => setEditing(null)}><form className="modal" onSubmit={submit} onClick={(e)=>e.stopPropagation()}><p className="eyebrow">{editing === 'new' ? 'CREATE MODEL' : 'UPDATE MODEL'}</p><h2>{editing === 'new' ? 'Them model' : 'Sua model'}</h2><label>Model ID<input value={form.id} disabled={editing !== 'new'} onChange={(e)=>setForm({...form,id:e.target.value})} required/></label><label>Ten hien thi<input value={form.displayName} onChange={(e)=>setForm({...form,displayName:e.target.value})} required/></label><label>Provider<input value={form.provider} onChange={(e)=>setForm({...form,provider:e.target.value})} required/></label><div className="form-columns"><label>Gia input / 1M<input type="number" min="0" value={form.inputPrice} onChange={(e)=>setForm({...form,inputPrice:Number(e.target.value)})}/></label><label>Gia output / 1M<input type="number" min="0" value={form.outputPrice} onChange={(e)=>setForm({...form,outputPrice:Number(e.target.value)})}/></label></div><label className="switch-row"><span><b>Dang kinh doanh</b><small>Cho phep cap model nay cho tai khoan.</small></span><input type="checkbox" checked={form.enabled} onChange={(e)=>setForm({...form,enabled:e.target.checked})}/></label>{save.isError && <p className="form-error">Khong the luu model. Kiem tra ID hoac du lieu nhap.</p>}<div className="modal-actions"><button type="button" className="button ghost" onClick={()=>setEditing(null)}>Huy</button><button className="button primary">Luu model</button></div></form></div>}
    {bulkPricing&&<div className="modal-layer" onClick={()=>setBulkPricing(false)}><form className="modal bulk-pricing-modal" onSubmit={(event)=>{event.preventDefault();applyBulk.mutate({input:bulkForm.inputPrice,output:bulkForm.outputPrice});}} onClick={(event)=>event.stopPropagation()}><div className="bulk-pricing-head"><span className="confirm-icon pricing"><Calculator/></span><div><p className="eyebrow">BULK PRICING</p><h2>Áp giá model hàng loạt</h2><p>Cập nhật đồng thời các model trong phạm vi tìm kiếm hiện tại.</p></div></div><div className="bulk-scope"><div><span>PHẠM VI ÁP DỤNG</span><strong>{filtered.length} model</strong></div><small>{query?`Bộ lọc: “${query}”`:'Toàn bộ model trong catalog'}</small></div><div className="form-columns"><label>Giá input / 1M token<input type="number" min="0" step="1" value={bulkForm.inputPrice} onChange={(event)=>setBulkForm({...bulkForm,inputPrice:Number(event.target.value)})} required/><small>{formatVnd(bulkForm.inputPrice/1_000_000)} / token</small></label><label>Giá output / 1M token<input type="number" min="0" step="1" value={bulkForm.outputPrice} onChange={(event)=>setBulkForm({...bulkForm,outputPrice:Number(event.target.value)})} required/><small>{formatVnd(bulkForm.outputPrice/1_000_000)} / token</small></label></div><div className="bulk-price-preview"><div><span>INPUT</span><b>{formatVnd(bulkForm.inputPrice)}</b><small>/ 1 triệu token</small></div><div><span>OUTPUT</span><b>{formatVnd(bulkForm.outputPrice)}</b><small>/ 1 triệu token</small></div></div><div className="confirm-note"><Activity/><span>Giá hiện tại của {filtered.length} model sẽ được thay thế ngay sau khi xác nhận.</span></div>{applyBulk.isError&&<p className="form-error">Không thể cập nhật giá. Vui lòng kiểm tra dữ liệu và thử lại.</p>}<div className="modal-actions"><button type="button" className="button ghost" onClick={()=>setBulkPricing(false)} disabled={applyBulk.isPending}>Hủy</button><button className="button primary" disabled={applyBulk.isPending||!filtered.length}><Calculator/>{applyBulk.isPending?'Đang cập nhật...':`Áp giá cho ${filtered.length} model`}</button></div></form></div>}
    {calculator&&<div className="modal-layer" onClick={()=>setCalculator(null)}><article className="modal cost-calculator" onClick={event=>event.stopPropagation()}><p className="eyebrow">TOKEN COST CALCULATOR</p><h2>{calculator.displayName}</h2><p>Công thức backend đang dùng: làm tròn [(input token × giá input / 1.000.000) + (output token × giá output / 1.000.000)].</p><div className="form-columns"><label>Input token<input type="number" min="0" value={sampleTokens.input} onChange={event=>setSampleTokens({...sampleTokens,input:Number(event.target.value)})}/></label><label>Output token<input type="number" min="0" value={sampleTokens.output} onChange={event=>setSampleTokens({...sampleTokens,output:Number(event.target.value)})}/></label></div><div className="cost-breakdown"><div><span>Input</span><b>{sampleTokens.input.toLocaleString('vi-VN')} × {formatVnd(calculator.inputPrice)} / 1M</b><strong>{formatVnd(sampleTokens.input*calculator.inputPrice/1_000_000)}</strong></div><div><span>Output</span><b>{sampleTokens.output.toLocaleString('vi-VN')} × {formatVnd(calculator.outputPrice)} / 1M</b><strong>{formatVnd(sampleTokens.output*calculator.outputPrice/1_000_000)}</strong></div><div className="cost-total"><span>Tổng trừ ví</span><b>{(sampleTokens.input+sampleTokens.output).toLocaleString('vi-VN')} token</b><strong>{formatVnd(Math.round(sampleTokens.input*calculator.inputPrice/1_000_000+sampleTokens.output*calculator.outputPrice/1_000_000))}</strong></div></div><div className="modal-actions"><button className="button primary" onClick={()=>setCalculator(null)}>Đã hiểu</button></div></article></div>}
  </div>;
}
