import { useMutation, useQuery, useQueryClient } from '@tanstack/react-query';
import { AlertTriangle, CheckCheck, Coins, Edit3, Gauge, LockKeyhole, RefreshCw, Search, Settings2, Trash2, UserPlus, X } from 'lucide-react';
import { FormEvent, useMemo, useState } from 'react';
import { apiClient } from '../../../core/api/client';
import type { Model, User } from '../../../core/types';
import { PageHeader } from '../../../shared/components/PageHeader';
import { Badge } from '../../../shared/components/Badge';
import { formatNumber, formatVnd } from '../../../shared/utils/format';
import { usePagination } from '../../../shared/hooks/usePagination';
import { TablePagination } from '../../../shared/components/TablePagination';
import { TableEmpty } from '../../../shared/components/TableEmpty';

type Modal = { type: 'create' } | { type: 'edit' | 'balance' | 'tokens' | 'models'; user: User } | null;

export function UsersPage() {
  const client = useQueryClient();
  const [query, setQuery] = useState('');
  const [modal, setModal] = useState<Modal>(null);
  const [userForm, setUserForm] = useState({ name: '', email: '', password: '', token_quota: 0 });
  const [balanceForm, setBalanceForm] = useState({ amount: 100000, token_amount: 0, type: 'credit', description: 'Admin credit' });
  const [tokenForm, setTokenForm] = useState({ operation: 'credit', amount: 1000000, description: 'Admin token adjustment' });
  const [modelQuery, setModelQuery] = useState('');
  const [selectedModels, setSelectedModels] = useState<string[]>([]);
  const [archivingUser, setArchivingUser] = useState<User | null>(null);
  const { data: users = [], isFetching: loadingUsers, refetch: refetchUsers } = useQuery({
    queryKey: ['admin-users'],
    queryFn: async () => (await apiClient.get<User[]>('/admin/users')).data,
    refetchInterval: 10_000,
    refetchOnWindowFocus: true,
    staleTime: 0,
  });
  const { data: models = [] } = useQuery({ queryKey: ['admin-models'], queryFn: async () => (await apiClient.get<Model[]>('/admin/router/models')).data });
  const filtered = useMemo(() => users.filter((u) => `${u.id} ${u.name} ${u.email}`.toLowerCase().includes(query.toLowerCase())), [users, query]);
  const pagination = usePagination(filtered, 10);
  const refresh = () => client.invalidateQueries({ queryKey: ['admin-users'] });
  const close = () => setModal(null);
  const create = useMutation({ mutationFn: () => apiClient.post('/admin/users', userForm), onSuccess: () => { refresh(); close(); } });
  const update = useMutation({ mutationFn: (user: User) => apiClient.put(`/admin/users/${user.id}`, userForm), onSuccess: () => { refresh(); close(); } });
  const adjust = useMutation({ mutationFn: (user: User) => apiClient.post(`/admin/users/${user.id}/balance`, balanceForm), onSuccess: () => { refresh(); close(); client.invalidateQueries({queryKey:['finance']}); } });
  const adjustTokens = useMutation({ mutationFn: (user: User) => apiClient.post(`/admin/users/${user.id}/tokens`, tokenForm), onSuccess: () => { refresh(); close(); } });
  const toggleStatus = useMutation({ mutationFn: (id: number) => apiClient.patch(`/admin/users/${id}/status`), onSuccess: refresh });
  const archive = useMutation({ mutationFn: (id: number) => apiClient.delete(`/admin/users/${id}`), onSuccess: () => { refresh(); setArchivingUser(null); } });
  const permanentlyDelete = useMutation({ mutationFn: (id: number) => apiClient.delete(`/admin/users/${id}/permanent`), onSuccess: () => { refresh(); setArchivingUser(null); } });
  const setModels = useMutation({ mutationFn: ({ userId, modelIds }: { userId: number; modelIds: string[] }) => apiClient.put(`/admin/users/${userId}/models`, { model_ids: modelIds }), onSuccess: refresh });

  function openCreate() { setUserForm({ name: '', email: '', password: '', token_quota: 0 }); setModal({type:'create'}); }
  function openEdit(user: User) { setUserForm({ name:user.name, email:user.email, password:'', token_quota:user.tokenQuota }); setModal({type:'edit',user}); }
  function openModels(user: User) { setSelectedModels(user.models); setModelQuery(''); setModal({type:'models',user}); }
  function toggleModel(modelId: string) { setSelectedModels((current) => current.includes(modelId) ? current.filter((id) => id !== modelId) : [...current, modelId]); }
  function submitUser(e: FormEvent) { e.preventDefault(); if (modal?.type === 'create') create.mutate(); else if (modal?.type === 'edit') update.mutate(modal.user); }

  return <div className="page">
    <PageHeader eyebrow="SUPER ADMIN / ACCOUNTS" title="Quản lý tài khoản" description="Tài khoản tự đăng ký được đồng bộ tự động mỗi 10 giây." action={<div className="row-actions"><button className="button ghost" onClick={()=>refetchUsers()} disabled={loadingUsers}><RefreshCw className={loadingUsers?'spin':''}/> {loadingUsers?'Đang tải...':'Làm mới'}</button><button className="button primary" onClick={openCreate}><UserPlus/> Tạo tài khoản</button></div>} />
    <div className="toolbar"><div className="search"><Search/><input value={query} onChange={(e) => setQuery(e.target.value)} placeholder="Tim ten, email, ID..."/></div><Badge tone="success">{users.filter((u) => u.status === 'active').length} DANG HOAT DONG</Badge></div>
    <article className="card table-card"><div className="table-section-heading"><div><p className="eyebrow">CLIENT DIRECTORY</p><h3>Danh sach tai khoan</h3></div><span>{filtered.length} ket qua</span></div>{filtered.length ? <div className="table-wrap"><table><thead><tr><th>Khach hang</th><th>So du</th><th>Token quota</th><th>Model da cap</th><th>Trang thai</th><th>Thao tac</th></tr></thead><tbody>{pagination.paginatedItems.map((user) => <tr key={user.id}>
      <td><div className="user-cell"><span className="avatar">{user.name.slice(0,2).toUpperCase()}</span><span><b>{user.name}</b><small>{user.email} · #{user.id}</small></span></div></td>
      <td><b>{formatVnd(user.balance)}</b></td><td>{user.tokenQuota>0?<><b>{formatNumber(Math.max(0,user.tokenQuota-user.tokenUsed))} còn lại</b><small className="block">Đã dùng {formatNumber(user.tokenUsed)} / {formatNumber(user.tokenQuota)}</small></>:<><b>Không giới hạn</b><small className="block">Đã dùng {formatNumber(user.tokenUsed)} · tính phí theo ví</small></>}</td>
      <td><div className="model-entitlement-summary"><div className="model-count"><b>{user.models.length}</b><span>model</span></div><div className="model-preview">{user.models.slice(0,2).map((id) => <span key={id}>{id}</span>)}{user.models.length > 2 && <span className="more">+{user.models.length - 2}</span>}{!user.models.length && <small>Chưa được cấp model</small>}</div><button className="button ghost compact" onClick={() => openModels(user)}><Settings2/> Quản lý</button></div></td>
      <td><Badge tone={user.status === 'active' ? 'success' : user.status === 'archived' ? 'neutral' : 'danger'}>{user.status.toUpperCase()}</Badge></td>
      <td><div className="row-actions"><button className="icon-button" title="Sua" onClick={() => openEdit(user)}><Edit3/></button><button className="icon-button" title="Dieu chinh so du" onClick={() => { setBalanceForm({amount:100000,token_amount:0,type:'credit',description:'Admin credit'}); setModal({type:'balance',user}); }}><Coins/></button><button className="icon-button" title="Dieu chinh token rieng" onClick={() => { setTokenForm({operation:'credit',amount:1000000,description:'Admin token adjustment'}); setModal({type:'tokens',user}); }}><Gauge/></button><button className="icon-button" title="Khoa/mo" onClick={() => toggleStatus.mutate(user.id)}><LockKeyhole/></button><button className="icon-button danger-text" title="Lưu trữ" onClick={() => setArchivingUser(user)}><Trash2/></button></div></td>
    </tr>)}</tbody></table></div> : <TableEmpty message="Thu thay doi tu khoa tim kiem hoac tao tai khoan moi."/>}<TablePagination page={pagination.page} pageSize={pagination.pageSize} totalItems={pagination.totalItems} totalPages={pagination.totalPages} onPageChange={pagination.setPage} onPageSizeChange={pagination.changePageSize}/></article>

    {(modal?.type === 'create' || modal?.type === 'edit') && <div className="modal-layer" onClick={close}><form className="modal" onSubmit={submitUser} onClick={(e) => e.stopPropagation()}><p className="eyebrow">{modal.type === 'create' ? 'NEW CLIENT' : 'UPDATE CLIENT'}</p><h2>{modal.type === 'create' ? 'Tao tai khoan' : `Sua ${modal.user.name}`}</h2><label>Ho ten<input value={userForm.name} onChange={(e) => setUserForm({...userForm,name:e.target.value})} required/></label><label>Email<input type="email" value={userForm.email} onChange={(e) => setUserForm({...userForm,email:e.target.value})} required/></label><label>{modal.type === 'create' ? 'Mat khau' : 'Mat khau moi (de trong neu khong doi)'}<input type="password" minLength={8} value={userForm.password} onChange={(e) => setUserForm({...userForm,password:e.target.value})} required={modal.type === 'create'}/></label>{modal.type === 'edit' && <label>Token quota<input type="number" min="0" value={userForm.token_quota} onChange={(e) => setUserForm({...userForm,token_quota:Number(e.target.value)})}/></label>}<ModalActions close={close} pending={create.isPending || update.isPending}/></form></div>}
    {modal?.type === 'balance' && <div className="modal-layer" onClick={close}><form className="modal" onSubmit={(e) => {e.preventDefault();adjust.mutate(modal.user);}} onClick={(e) => e.stopPropagation()}><p className="eyebrow">WALLET ADJUSTMENT</p><h2>Dieu chinh so du</h2><p>{modal.user.name} · hien co {formatVnd(modal.user.balance)}</p><label>Loai<select value={balanceForm.type} onChange={(e) => setBalanceForm({...balanceForm,type:e.target.value})}><option value="credit">Cong tien</option><option value="debit">Tru tien</option></select></label><label>So tien<input type="number" min="1" value={balanceForm.amount} onChange={(e) => setBalanceForm({...balanceForm,amount:Number(e.target.value)})}/></label><label>Ly do<input value={balanceForm.description} onChange={(e) => setBalanceForm({...balanceForm,description:e.target.value})}/></label><ModalActions close={close} pending={adjust.isPending}/></form></div>}
    {modal?.type === 'tokens' && <div className="modal-layer" onClick={close}><form className="modal" onSubmit={(e) => {e.preventDefault();adjustTokens.mutate(modal.user);}} onClick={(e) => e.stopPropagation()}><p className="eyebrow">OPTIONAL SAFETY LIMIT</p><h2>Hạn mức token của {modal.user.name}</h2><div className="deposit-estimate"><span>TRẠNG THÁI</span><strong>{modal.user.tokenQuota>0?formatNumber(Math.max(0,modal.user.tokenQuota-modal.user.tokenUsed)):'Không giới hạn'}</strong><small>Đã dùng {formatNumber(modal.user.tokenUsed)}{modal.user.tokenQuota>0?` · Tổng quota ${formatNumber(modal.user.tokenQuota)}`:' · Thanh toán theo số dư ví'}</small></div><label>Thao tác<select value={tokenForm.operation} onChange={(e) => setTokenForm({...tokenForm,operation:e.target.value})}><option value="set">Đặt tổng quota</option><option value="credit">Cộng thêm token</option><option value="debit">Trừ bớt token</option></select></label><label>{tokenForm.operation==='set'?'Tổng quota mới (0 = không giới hạn)':'Số token thay đổi'}<input type="number" min="0" step="1000" value={tokenForm.amount} onChange={(e) => setTokenForm({...tokenForm,amount:Number(e.target.value)})}/></label><p className="muted">Quota chỉ là giới hạn an toàn. Chi phí thực tế luôn được trừ theo giá input/output trong ví.</p><label>Lý do<input value={tokenForm.description} onChange={(e) => setTokenForm({...tokenForm,description:e.target.value})} required minLength={3}/></label><ModalActions close={close} pending={adjustTokens.isPending}/></form></div>}
    {modal?.type === 'models' && <div className="modal-layer" onClick={close}><form className="modal model-manager-modal" onSubmit={(e) => {e.preventDefault();setModels.mutate({userId:modal.user.id,modelIds:selectedModels},{onSuccess:close});}} onClick={(e) => e.stopPropagation()}><div className="model-manager-head"><div><p className="eyebrow">MODEL ENTITLEMENTS</p><h2>Model của {modal.user.name}</h2><p>{selectedModels.length}/{models.filter((m) => m.enabled).length} model được chọn</p></div><span className="avatar">{modal.user.name.slice(0,2).toUpperCase()}</span></div><div className="model-manager-toolbar"><div className="search"><Search/><input value={modelQuery} onChange={(e)=>setModelQuery(e.target.value)} placeholder="Tìm model hoặc provider..."/></div><button type="button" className="button ghost compact" onClick={()=>setSelectedModels(models.filter((m)=>m.enabled).map((m)=>m.id))}><CheckCheck/> Chọn tất cả</button><button type="button" className="button ghost compact danger-text" onClick={()=>setSelectedModels([])}><X/> Bỏ tất cả</button></div><div className="model-picker-grid">{models.filter((m)=>m.enabled && `${m.id} ${m.displayName} ${m.provider}`.toLowerCase().includes(modelQuery.toLowerCase())).map((model)=><label className={selectedModels.includes(model.id)?'selected':''} key={model.id}><input type="checkbox" checked={selectedModels.includes(model.id)} onChange={()=>toggleModel(model.id)}/><span><b>{model.displayName}</b><small>{model.id}</small></span><em>{model.provider}</em></label>)}</div><div className="modal-actions"><button type="button" className="button ghost" onClick={close}>Hủy</button><button className="button primary" disabled={setModels.isPending}><CheckCheck/>{setModels.isPending?'Đang lưu...':`Lưu ${selectedModels.length} model`}</button></div></form></div>}
    {archivingUser && <div className="modal-layer" onClick={()=>setArchivingUser(null)}><article className="modal confirm-modal" onClick={(e)=>e.stopPropagation()}><div className="confirm-icon danger"><AlertTriangle/></div><p className="eyebrow">{archivingUser.status==='archived'?'XÓA VĨNH VIỄN':'XÁC NHẬN LƯU TRỮ'}</p><h2>{archivingUser.status==='archived'?'Xóa vĩnh viễn tài khoản?':'Lưu trữ tài khoản?'}</h2><p className="confirm-description">{archivingUser.status==='archived'?'Toàn bộ API key, quyền model, giao dịch, đơn nạp và nhật ký của tài khoản sẽ bị xóa hoàn toàn.':'Tài khoản sẽ không thể tiếp tục sử dụng API và đăng nhập cho đến khi được kích hoạt lại.'}</p><div className="confirm-target"><span className="avatar">{archivingUser.name.slice(0,2).toUpperCase()}</span><div><b>{archivingUser.name}</b><small>{archivingUser.email} · #{archivingUser.id}</small></div></div><div className="confirm-note"><AlertTriangle/><span>{archivingUser.status==='archived'?'Không thể hoàn tác sau khi xác nhận.':'Dữ liệu giao dịch và lịch sử vẫn được giữ lại.'}</span></div>{(archive.isError||permanentlyDelete.isError)&&<p className="form-error">Không thể thực hiện thao tác. Vui lòng thử lại.</p>}<div className="modal-actions"><button className="button ghost" onClick={()=>setArchivingUser(null)} disabled={archive.isPending||permanentlyDelete.isPending}>Hủy</button><button className="button danger" onClick={()=>archivingUser.status==='archived'?permanentlyDelete.mutate(archivingUser.id):archive.mutate(archivingUser.id)} disabled={archive.isPending||permanentlyDelete.isPending}><Trash2/>{archive.isPending?'Đang lưu trữ...':permanentlyDelete.isPending?'Đang xóa...':archivingUser.status==='archived'?'Xóa vĩnh viễn':'Lưu trữ tài khoản'}</button></div></article></div>}
  </div>;
}

function ModalActions({close,pending}:{close:()=>void;pending:boolean}) { return <div className="modal-actions"><button type="button" className="button ghost" onClick={close}>Huy</button><button className="button primary" disabled={pending}>{pending ? 'Dang xu ly...' : 'Luu thay doi'}</button></div>; }
