import {useMutation,useQuery,useQueryClient} from '@tanstack/react-query';
import {Copy,Plus,QrCode} from 'lucide-react';
import {FormEvent,useState} from 'react';
import {apiClient} from '../../../core/api/client';
import {Badge} from '../../../shared/components/Badge';
import {PageHeader} from '../../../shared/components/PageHeader';
import {TableEmpty} from '../../../shared/components/TableEmpty';
import {TablePagination} from '../../../shared/components/TablePagination';
import {usePagination} from '../../../shared/hooks/usePagination';
import {formatVnd} from '../../../shared/utils/format';

interface Transaction{id:number;createdAt:string;type:'credit'|'debit';amount:number;description:string}
interface Bank{id:number;bankCode:string;bankName:string;accountNumber:string;accountName:string}
interface Deposit{id:number;code:string;expectedAmount:number;paidAmount:number;status:string;expiresAt:string;qrUrl:string;bank:Bank}
export function WalletPage(){
 const client=useQueryClient(),[adding,setAdding]=useState(false),[amount,setAmount]=useState(10000),[bankId,setBankId]=useState(0),[selected,setSelected]=useState<Deposit|null>(null);
 const{data=[]}=useQuery({queryKey:['transactions'],queryFn:async()=>(await apiClient.get<Transaction[]>('/wallet/transactions')).data,refetchInterval:5000});
 const{data:banks=[]}=useQuery({queryKey:['wallet-banks'],queryFn:async()=>(await apiClient.get<Bank[]>('/wallet/bank-accounts')).data});
 const{data:deposits=[]}=useQuery({queryKey:['deposits'],queryFn:async()=>(await apiClient.get<Deposit[]>('/wallet/deposits')).data,refetchInterval:5000});
 const create=useMutation({mutationFn:async()=>(await apiClient.post<Deposit>('/wallet/deposits',{bank_account_id:bankId||banks[0]?.id,amount})).data,onSuccess:item=>{client.invalidateQueries({queryKey:['deposits']});setAdding(false);setSelected(item)}});
 const balance=data.reduce((sum,item)=>sum+(item.type==='credit'?item.amount:-item.amount),0),pagination=usePagination(data,10);
 function submit(e:FormEvent){e.preventDefault();create.mutate()}
 return <div className="page"><PageHeader eyebrow="ACCOUNT / FUNDS" title="Ví & giao dịch" description="Bạn chọn số tiền muốn nạp; hệ thống tự tính chi phí theo model khi sử dụng." action={<button className="button primary" disabled={!banks.length} onClick={()=>setAdding(true)}><Plus/> Nạp qua QR</button>}/><section className="hero-balance compact"><div><p className="eyebrow">SỐ DƯ KHẢ DỤNG</p><strong>{formatVnd(balance)}</strong><span>Đối soát tự động từ ngân hàng</span></div></section>
 {deposits.length>0&&<article className="card table-card"><div className="table-section-heading"><div><p className="eyebrow">DEPOSIT ORDERS</p><h3>Yêu cầu nạp gần đây</h3></div><span>Tự kiểm tra mỗi 5 giây</span></div><div className="table-wrap"><table><thead><tr><th>Mã chuyển khoản</th><th>Số tiền</th><th>Trạng thái</th><th>QR</th></tr></thead><tbody>{deposits.slice(0,5).map(item=><tr key={item.id}><td><b>{item.code}</b></td><td>{formatVnd(item.expectedAmount)}</td><td><Badge tone={item.status==='paid'?'success':item.status==='pending'?'warning':'neutral'}>{item.status.toUpperCase()}</Badge></td><td><button className="icon-button" onClick={()=>setSelected(item)}><QrCode/></button></td></tr>)}</tbody></table></div></article>}
 <article className="card table-card"><div className="table-section-heading"><div><p className="eyebrow">LEDGER</p><h3>Lịch sử giao dịch</h3></div><span>{data.length} giao dịch</span></div>{data.length?<div className="table-wrap"><table><thead><tr><th>Thời gian</th><th>Loại</th><th>Số tiền</th><th>Nội dung</th></tr></thead><tbody>{pagination.paginatedItems.map(tx=><tr key={tx.id}><td>{tx.createdAt}</td><td><Badge tone={tx.type==='credit'?'success':'warning'}>{tx.type.toUpperCase()}</Badge></td><td className={tx.type}>{tx.type==='credit'?'+':'-'}{formatVnd(tx.amount)}</td><td>{tx.description}</td></tr>)}</tbody></table></div>:<TableEmpty/>}<TablePagination page={pagination.page} pageSize={pagination.pageSize} totalItems={pagination.totalItems} totalPages={pagination.totalPages} onPageChange={pagination.setPage} onPageSizeChange={pagination.changePageSize}/></article>
 {adding&&<div className="modal-layer" onClick={()=>setAdding(false)}><form className="modal" onSubmit={submit} onClick={e=>e.stopPropagation()}><p className="eyebrow">CREATE DEPOSIT</p><h2>Bạn muốn nạp bao nhiêu?</h2><label>Ngân hàng nhận<select value={bankId||banks[0]?.id||''} onChange={e=>setBankId(Number(e.target.value))}>{banks.map(item=><option key={item.id} value={item.id}>{item.bankName} · {item.accountNumber}</option>)}</select></label><label>Số tiền muốn nạp<input type="number" min="1000" step="1000" value={amount} onChange={e=>setAmount(Number(e.target.value))}/></label><p>Số tiền này được cộng vào ví. Token được tính theo giá input/output của model do admin cấu hình, không phụ thuộc ngân hàng.</p><div className="modal-actions"><button type="button" className="button ghost" onClick={()=>setAdding(false)}>Hủy</button><button className="button primary" disabled={create.isPending}>Tạo VietQR</button></div></form></div>}
 {selected&&<div className="modal-layer" onClick={()=>setSelected(null)}><article className="modal qr-payment" onClick={e=>e.stopPropagation()}><p className="eyebrow">SCAN TO PAY</p><h2>{formatVnd(selected.expectedAmount)}</h2><img src={selected.qrUrl} alt="VietQR chuyển khoản"/><dl><dt>Ngân hàng</dt><dd>{selected.bank.bankName}</dd><dt>Số tài khoản</dt><dd>{selected.bank.accountNumber}</dd><dt>Nội dung bắt buộc</dt><dd><b>{selected.code}</b><button className="icon-button" onClick={()=>navigator.clipboard.writeText(selected.code)}><Copy/></button></dd></dl><p>Sau khi webhook xác nhận, toàn bộ số tiền thực nhận sẽ tự cộng vào ví.</p><div className="modal-actions"><button className="button primary" onClick={()=>setSelected(null)}>Đã hiểu</button></div></article></div>}</div>;
}
